// Code generated by tygo. DO NOT EDIT.

//////////
// source: schema.go

/**
 * Config is the top-level orbit.yaml structure.
 */
export interface Config {
  version: string;
  /**
   * PreviewOnly marks the env as inspectable but not activatable on
   * this machine. The daemon rejects switch attempts (CLI and UI
   * both go through the same endpoint, so both paths are covered).
   * Defends the active machine from misclicks; not a security
   * boundary — a user with write access to the yaml can flip it.
   */
  previewOnly: boolean;
  settings: RuntimeSettings;
  groups: { [key: string]: Group};
  containers: { [key: string]: Container | undefined};
  services: { [key: string]: Service | undefined};
  externals: { [key: string]: External | undefined};
  /**
   * Tracing is the local OpenTelemetry section. When on, the daemon runs an
   * OTLP/HTTP receiver and injects OTEL_* env into dev services so their
   * spans flow into Orbit. Tracing is on unless the environment explicitly
   * sets enabled: false. See Config.TracingEnabled.
   */
  tracing?: TracingConfig;
}
/**
 * TracingConfig configures the built-in local OTLP receiver. The receiver is
 * HTTP-only (OTLP/HTTP on OTLPPort); services are pointed at it by injecting
 * OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf. Spans live in an in-memory ring
 * buffer of at most MaxTraces traces and are dropped on `orbit down`.
 */
export interface TracingConfig {
  enabled?: boolean;
  otlp_port: number /* int */; // OTLP/HTTP receiver port; default 4318
  max_traces: number /* int */; // ring-buffer capacity in traces; default 1000
}
export interface RuntimeSettings {
  shutdown_timeout: number;
  health_check_interval: number;
  docker_poll_interval: number;
}
/**
 * Group is a named collection of services. It serves two purposes:
 *  1. Startup batching — `orbit up --groups X` brings up only the
 *     services listed under group X.
 *  2. Visual clustering on the dashboard (preview-only envs draw each
 *     group as a labeled box around its services).
 * Color is a free-form CSS color (e.g. "#d97706"). When empty the UI
 * derives a stable hue from the group name.
 */
export interface Group {
  enabled: boolean;
  color?: string;
  services: string[];
}
/**
 * KafkaIO is the optional kafka section on services and externals.
 * Listed topics are literal strings — no pattern matching. produces
 * and consumes are independent: a service can produce, consume, both,
 * or neither.
 */
export interface KafkaIO {
  produces: string[];
  consumes: string[];
}
/**
 * External is an out-of-workspace producer/consumer (e.g. an upstream
 * feed, a 3rd-party payment provider). It is rendered as a placeholder
 * node so async edges to/from external systems are visible on the
 * canvas. Externals never participate in startup; the daemon never
 * tries to launch them.
 */
export interface External {
  label: string;
  color?: string;
  kafka: KafkaIO;
}
export interface Container {
  image: string;
  icon: string;
  pull_policy: string; // always, if_not_present, never
  platform: string; // e.g. linux/amd64
  ports: { [key: string]: PortDef};
  environment: { [key: string]: string};
  volumes: string[];
  command: string[];
  user: string; // docker --user, e.g. "0:0"; needed by images that require root on a fresh named volume
  entrypoint: string[];
  health_check?: HealthCheckConfig;
  init?: InitConfig;
  seed?: SeedConfig;
  sidecars: Sidecar[];
  depends_on: string[];
  kind: string; // frontend | backend | infra
}
/**
 * PortDef supports both simple (6379) and mapped (8989:8080) port definitions.
 * YAML: `redis: 6379` or `ui: "8989:8080"` (host:container)
 */
export interface PortDef {
  Host: number /* int */;
  Target: number /* int */; // container-internal port; same as Host if not specified
}
export interface Sidecar {
  name: string;
  image: string;
  pull_policy: string;
  ports: { [key: string]: PortDef};
  environment: { [key: string]: string};
  volumes: string[];
  depends_on: string[];
}
export interface SeedConfig {
  command: string; // command inside the container; seed file is provided on stdin
  files: string[]; // seed file paths, executed in order
}
export interface InitConfig {
  type: string; // kafka_topics, mongo_rs
  topics_file: string;
  rs_members: string[];
}
export interface Service {
  type: string; // dotnet, node
  path: string;
  command: string;
  watch: boolean; // use file watcher (dotnet watch), default false
  url: string; // entry point URL for orbit open
  ports: { [key: string]: PortDef};
  env: { [key: string]: string};
  build_env: { [key: string]: string}; // env vars passed to the build step only (e.g. dotnet build), not to the running process
  env_toggles: { [key: string]: EnvToggle};
  health_check?: HealthCheckConfig;
  depends_on: string[];
  pre_start: string[];
  kind: string; // frontend | backend | infra
  kafka: KafkaIO;
}
/**
 * EnvToggle defines a toggleable environment variable.
 */
export interface EnvToggle {
  label: string;
  description: string;
  default: boolean;
}
export interface HealthCheckConfig {
  type: string; // http, tcp, log, exec, healthcheck
  path: string;
  port: number /* int */;
  pattern: string; // regex for "log" type
  command: string[]; // argv for "exec" type
  interval: number;
  timeout: number;
  retries: number /* int */;
  failure_threshold: number /* int */;
}
export type SchemaVersionMismatchKind = string;
export const SchemaVersionMissing: SchemaVersionMismatchKind = "missing";
export const SchemaVersionOlder: SchemaVersionMismatchKind = "older";
export const SchemaVersionNewer: SchemaVersionMismatchKind = "newer";
export const SchemaVersionInvalid: SchemaVersionMismatchKind = "invalid";
export interface SchemaVersionMismatchError {
  Path: string;
  Found: string;
  Supported: string;
  Kind: SchemaVersionMismatchKind;
}
