// Code generated by tygo. DO NOT EDIT.
import type { HealthProgressInfo, SidecarInfo } from './wire.gen'
import type { KafkaIO } from "./config.gen";

//////////
// source: config_staleness.go


//////////
// source: config_write.go


//////////
// source: doctor.go


//////////
// source: doctor_project_dependencies.go


//////////
// source: envs.go

/**
 * EnvSwitchRequest is the PUT body for /api/env.
 */
export interface EnvSwitchRequest {
  env: string; // short name (no .yaml) OR absolute path
  confirmed?: boolean;
  current_identity?: string;
  target_identity?: string;
}

//////////
// source: handlers_env_toggles.go

/**
 * EnvToggleInfo is the API response type for a single toggle.
 */
export interface EnvToggleInfo {
  service: string;
  var: string;
  value: string;
  label: string;
  description: string;
  enabled: boolean;
  default: boolean;
}

//////////
// source: handlers_graph.go

/**
 * GraphResponse is the response for GET /api/graph.
 */
export interface GraphResponse {
  env: string;
  /**
   * Groups maps group name → service names declared in that group. The UI
   * uses it to cluster service nodes by group.
   * Only groups with at least one service are included. Order is
   * deterministic (sorted by group name) so the canvas doesn't reshuffle
   * on each poll.
   */
  groups?: GroupInfo[];
  nodes: GraphNode[];
  edges: GraphEdge[];
}
/**
 * GroupInfo is one entry in GraphResponse.Groups. Kept as a slice (not a
 * map) so the order is deterministic without the UI having to re-sort.
 * Color forwards the yaml-provided color so the UI can theme each group
 * box; empty means "derive a stable hue from the name on the client".
 */
export interface GroupInfo {
  name: string;
  color?: string;
  services: string[];
}
/**
 * GraphNode is one node in the dependency graph. Kind here is the display
 * category (frontend|backend|infra), not the daemon's topology Kind which
 * is "service" vs "container".
 */
export interface GraphNode {
  name: string;
  kind: string; // frontend | backend | infra | external
  icon?: string;
  label?: string; // externals only; display name
  color?: string; // externals only; hex color tint
  state: string;
  /**
   * StateReason says why the node is degraded; empty otherwise.
   */
  stateReason?: string;
  failureKind?: string;
  blockedBy?: string;
  portConflict?: GraphPortConflict;
  logsAvailable?: boolean;
  mode?: string; // services only
  url?: string;
  ports?: { [key: string]: number /* int */};
  health?: HealthProgressInfo;
  sidecars?: SidecarInfo[]; // containers only — e.g. dbgate, mongo-express
  restart_count?: number /* int */;
  external_restart_count?: number /* int */;
  last_restart?: GraphRestart;
  startup_time?: string;
  uptime?: string;
  /**
   * Kafka carries the produces/consumes declarations the node owns.
   * Services with no declared topics get nil (omitted from JSON);
   * externals are required by validation to declare at least one
   * topic, so the pointer is always non-nil for them.
   */
  kafka?: KafkaIO;
}
export interface GraphRestart {
  source: string;
  started_at: string;
  observed_at: string;
}
export interface GraphPortConflict {
  port: number /* int */;
  resource: string;
  pid?: string;
  process?: string;
  inspect_command: string;
}
/**
 * EdgeKind distinguishes startup-time synchronous dependencies (the
 * existing model) from Kafka-mediated asynchronous producer/consumer
 * relationships introduced by Service.Kafka and Externals.
 */
export type EdgeKind = string;
export const EdgeKindSync: EdgeKind = "sync";
export const EdgeKindAsync: EdgeKind = "async";
/**
 * GraphEdge is one directed edge in the graph.
 */
export interface GraphEdge {
  from: string;
  to: string;
  kind: EdgeKind;
  topic?: string;
  detached: boolean;
  detachable: boolean;
  env_vars?: string[];
}

//////////
// source: handlers_service.go


//////////
// source: handlers_service_env.go

/**
 * ServiceEnvResponse is the response for GET /api/service-env/{name}.
 */
export interface ServiceEnvResponse {
  service: string;
  env: EnvVarEntry[];
}
/**
 * EnvVarEntry is one env var that will be (or is being) injected into the service process.
 */
export interface EnvVarEntry {
  key: string;
  value: string;
  source: string; // "explicit" | "toggle" | "dependency"
  /**
   * Dependency is the resource name this var came from when Source == "dependency".
   * Empty otherwise.
   */
  dependency?: string;
}

//////////
// source: handlers_settings.go


//////////
// source: history_middleware.go


//////////
// source: server.go

/**
 * Server is the daemon HTTP server that listens on a unix socket.
 */
export interface Server {
}

//////////
// source: sse.go


//////////
// source: version.go

