// Code generated by tygo. DO NOT EDIT.

//////////
// source: state.go
/*
Package dbstate tracks the most recent apply/reset/build/publish and
baseline refresh per database.
It is the canonical "what state is db X in" file. Audit history (the
full timeline of every command) is owned separately by internal/history.
*/

export type Source = string;
export const SourceUI: Source = "ui";
export const SourceCLI: Source = "cli";
/**
 * Event records one occurrence of a db lifecycle action.
 */
export interface Event {
  at: string;
  source: Source;
  durationMs?: number /* int64 */;
}
/**
 * DBState is the most-recent snapshot of one database's lifecycle.
 * Fields requiring a held Store.mu for read are documented below.
 */
export interface DBState {
  name: string;
  /**
   * LastApply is non-nil when the running db carries a local delta on
   * top of the image baseline (i.e. an apply happened more recently
   * than any build or reset). Cleared whenever the baseline moves:
   * successful Reset / Build / PublishClean / SnapshotRefreshed.
   */
  lastApply?: Event;
  lastPublish?: Event;
  /**
   * BaselineAt records when reset's internal clean state was refreshed.
   */
  baselineAt?: Event;
  lastReset?: Event;
}
/**
 * Snapshot is the wire shape returned by GET /api/db-state and pushed
 * over the SSE stream. Snapshot rather than delta so a slow subscriber
 * converges on next event.
 */
export interface Snapshot {
  version: number /* int */;
  updatedAt: string;
  dbs: { [key: string]: DBState};
}
