// Code generated by tygo. DO NOT EDIT.

//////////
// source: state.go
/*
Package dbstate tracks the most recent apply/reset/build/publish and
baseline refresh per database.
It is the canonical "what state is db X in" file. Audit history (the
full timeline of every command) is owned separately by internal/history.
*/

export type Source = string;
export const SourceUI: Source = "ui";
export const SourceCLI: Source = "cli";
/**
 * Event records one occurrence of a db lifecycle action.
 */
export interface Event {
  at: string;
  source: Source;
  durationMs?: number /* int64 */;
}
/**
 * BuildEvent extends Event with the project that produced the image
 * baseline this db mirrors. Build is the only kind that doesn't 1:1
 * correspond to a db name on the CLI surface.
 * Fields are duplicated rather than embedded because tygo emits embedded
 * fields as a nested object (BuildEvent { Event: Event }), whereas Go's
 * encoding/json flattens them — the wire shape then disagrees with the
 * generated TS type. Flattening on the Go side keeps both ends consistent.
 */
export interface BuildEvent {
  at: string;
  source: Source;
  durationMs?: number /* int64 */;
  project: string;
}
/**
 * DBState is the most-recent snapshot of one database's lifecycle.
 * Fields requiring a held Store.mu for read are documented below.
 */
export interface DBState {
  name: string;
  /**
   * LastApply is non-nil when the running db carries a local delta on
   * top of the image baseline (i.e. an apply happened more recently
   * than any build or reset). Cleared whenever the baseline moves:
   * successful Reset / Build / PublishClean / SnapshotRefreshed.
   */
  lastApply?: Event;
  lastPublish?: Event;
  /**
   * BaselineAt records when reset's internal clean state was refreshed.
   */
  baselineAt?: Event;
  lastReset?: Event;
  lastBuild?: BuildEvent;
  /**
   * ResetPending: build's image step succeeded but the post-build
   * reset for this db failed. Cleared on next successful Reset.
   */
  resetPending?: boolean;
  resetError?: string;
}
/**
 * Snapshot is the wire shape returned by GET /api/db-state and pushed
 * over the SSE stream. Snapshot rather than delta so a slow subscriber
 * converges on next event.
 */
export interface Snapshot {
  version: number /* int */;
  updatedAt: string;
  dbs: { [key: string]: DBState};
}
