// Code generated by tygo. DO NOT EDIT.
// DiffResult comes from the hand-maintained sqlpublish types (see the
// sqlpublish note in tygo.yaml) — DBDiffResponse.result references it.
import type { DiffResult } from './sqlpublish.gen'

//////////
// source: db_feature.go


//////////
// source: db_gate.go

/**
 * ErrMsgDBNotConfigured is returned by every DB-workflow endpoint (and
 * reused verbatim by the CLI) when the active env doesn't opt in.
 */
export const ErrMsgDBNotConfigured = "SQL Server workflow not configured: add a sqlserver section to the active environment";

//////////
// source: db_name_resolve.go


//////////
// source: db_projects.go


//////////
// source: db_query.go


//////////
// source: dbops.go

/**
 * DBOpFrame is one `dbop` SSE event on the multiplexed /api/events
 * stream. Exactly one
 * field group is populated per Kind.
 */
export interface DBOpFrame {
  kind: string; // "idle" | "start" | "output" | "done"
  op?: string; // start: "publish"
  db?: string; // start
  all?: boolean; // start, publish only: publishing every database
  startedAt?: string; // start
  line?: string; // output
  ok: boolean; // done (always emitted so false is explicit)
  durationMs?: number /* int64 */; // done
  err?: string; // done (only when !OK)
  errorCode?: string; // done (only when !OK): stable hint key
}

//////////
// source: devdb.go

export interface DevDBProject {
  name: string;
  path: string;
  databases: string[];
}
export interface DevDBProjectsResponse {
  projects: DevDBProject[];
}
export interface DevDBMetaResponse {
  environment_path: string;
  environment_name: string;
  sql_server_image: string;
  /**
   * SQLServerPort is the container's published host port — the target
   * `orbit sqlserver publish` connects to from the host.
   */
  sql_server_port?: number /* int */;
  /**
   * SQLServerTarget is the publish target's runtime docker name. The
   * CLI resolves the configured password key by inspecting this container
   * so port and credentials always come from the same declared target.
   */
  sql_server_target?: string;
  /**
   * SQLServerService is the target's environment service name. The dashboard
   * uses it for health and navigation instead of assuming a conventional
   * container name.
   */
  sql_server_service?: string;
  /**
   * SQLServerUsername and SQLServerPasswordEnv identify the configured
   * login without exposing its secret value.
   */
  sql_server_username?: string;
  sql_server_password_env?: string;
  workspace_root: string;
  /**
   * DBConfigured mirrors the DB-workflow gate: false when the active env
   * has no explicit sqlserver section. CLI and dashboard hide the DB
   * workflow behind it. A pointer so consumers can fail OPEN when the
   * field is absent — a CLI newer than its daemon must not lock
   * users out of db commands just because the old daemon doesn't report it.
   * Interpret via WorkflowConfigured, not by dereferencing directly.
   */
  db_configured?: boolean;
  /**
   * ClaimConfigured is false when the active env has no claim section
   * (Tunlease tunnel support). The dashboard hides the Tunnels tab behind
   * it, the same way DBConfigured gates the SQL Server workflow. Same pointer +
   * fail-open rule: nil (a daemon predating the field) counts as
   * configured so the tab never wrongly vanishes for
   * users on an older daemon. Interpret via ClaimSupported.
   * This DB-named response carries the tunnel gate too — the pragmatic
   * choice over a second endpoint. If a third feature needs a UI gate,
   * promote this to a general feature-meta type.
   */
  claim_configured?: boolean;
}

//////////
// source: drift_cache.go

/**
 * DriftEntry is one database's cached diff outcome: either a structured
 * Result or a failure (Error + Code) — never both. At is the RFC3339
 * time the diff ran; Stale marks a publish/reset since then.
 */
export interface DriftEntry {
  db: string;
  result?: DiffResult;
  error?: string;
  code?: string;
  at: string;
  stale?: boolean;
}
/**
 * DriftSnapshotResponse is the body of GET /api/db/drift: every cached
 * entry in stable (by DB name) order.
 */
export interface DriftSnapshotResponse {
  entries: DriftEntry[];
}

//////////
// source: handlers_dbstate.go

/**
 * DBStateEventRequest is the body of POST /api/db-state/event.
 * CLI calls this after a DB operation (apply, reset, publish,
 * publish_clean, snapshot) succeeds or fails.
 */
export interface DBStateEventRequest {
  kind: string; // "apply" | "reset" | "publish" | "publish_clean" | "snapshot"
  db: string;
  source: any /* dbstate.Source */; // "ui" | "cli"
  status: string; // "ok" | "error"
  durationMs?: number /* int64 */;
  errorMsg?: string;
}

//////////
// source: handlers_diff.go

/**
 * DBDiffRequest is the body for POST /api/db/diff.
 */
export interface DBDiffRequest {
  db: string;
  /**
   * Script requests the full T-SQL deployment script instead of the
   * structured operation summary.
   */
  script?: boolean;
  /**
   * Analyze compares the dacpac with SQL Server to return exact object
   * operations and data-loss warnings.
   */
  analyze?: boolean;
  /**
   * FastOnly returns needs_engine instead of falling through to
   * sqlpackage. Page-entry refreshes use it so navigation stays cheap.
   */
  fast_only?: boolean;
}
/**
 * DBDiffResponse carries a structured result, a requested SQL script, or
 * NeedsEngine when a fast-only request cannot prove an answer.
 */
export interface DBDiffResponse {
  result?: DiffResult;
  script?: string;
  needs_engine?: boolean;
}

//////////
// source: handlers_publish.go

/**
 * DBPublishRequest is the body for POST /api/db/publish.
 */
export interface DBPublishRequest {
  /**
   * DB names one database; empty and ignored when All is set.
   */
  db?: string;
  force?: boolean;
  /**
   * All publishes every database from the project merge, sequentially
   * under the one op lock, stopping at the first failure.
   */
  all?: boolean;
}

//////////
// source: handlers_reset.go

/**
 * CodeResetRequiresConfirmation is returned when reset needs explicit
 * acknowledgement that local data will be discarded.
 */
export const CodeResetRequiresConfirmation = "reset_requires_confirmation";
/**
 * DBResetState lets clients explain the reset path before asking for
 * destructive confirmation. A database without a baseline must be recreated.
 */
export interface DBResetState {
  exists: boolean;
  hasBaseline: boolean;
}
/**
 * DBResetStateResponse maps each known database to its reset readiness.
 */
export interface DBResetStateResponse {
  states: { [key: string]: DBResetState};
}
/**
 * DBResetRequest is the body for POST /api/db/reset. The client never
 * selects the reset path. AcknowledgeDataLoss confirms the caller showed
 * that reset discards local data; the server still chooses the fastest
 * safe implementation.
 */
export interface DBResetRequest {
  db: string;
  acknowledgeDataLoss?: boolean;
}

//////////
// source: sqlserver_config.go

/**
 * SQLServerConfig is the explicit opt-in for SQL Server Database Projects.
 * Project paths are relative to the workspace so one shared env works across
 * developer machines without a second allowlist or DB-root setting.
 */
export interface SQLServerConfig {
  target: string;
  username: string;
  password_env: string;
  projects: SQLServerProjectConfig[];
}
export interface SQLServerProjectConfig {
  path: string;
  databases?: string[];
}
