// Code generated by tygo. DO NOT EDIT.
// DiffResult comes from the hand-maintained sqlpublish types (see the
// sqlpublish note in tygo.yaml) — DBDiffResponse.result references it.
import type { DiffResult } from './sqlpublish.gen'

//////////
// source: db_feature.go


//////////
// source: db_gate.go

/**
 * ErrMsgDBNotConfigured is returned by every DB-workflow endpoint (and
 * reused verbatim by the CLI) when the active env doesn't opt in.
 */
export const ErrMsgDBNotConfigured = "db workflow not configured: the active env declares neither a sql-server container nor sql_projects — see docs/team-adoption.md";
/**
 * SQLServerContainerName is the container name that opts an env into the
 * DB workflow. Exported so consumers (snapshots, doctor, CLI) reference
 * the concept instead of repeating the literal. Owned by the DB-workflow
 * gate domain — the core config schema no longer knows the convention
 * (spec B5/B6).
 */
export const SQLServerContainerName = "sql-server";

//////////
// source: db_name_resolve.go


//////////
// source: db_projects.go


//////////
// source: db_projects_config.go

/**
 * DBProjectsConfig is the allowlist of SQL-project directory names the DB
 * workflow publishes. Matching is case-insensitive (see dbProjectAllowlist):
 * the same project is cased differently across checkouts (billing.payment
 * vs Billing.Payment) and no one list spelling can be right for everyone.
 */
export interface DBProjectsConfig {
  projects: string[];
}

//////////
// source: dbops.go

/**
 * DBOpFrame is one `dbop` SSE event on the multiplexed /api/events
 * stream. Exactly one
 * field group is populated per Kind.
 */
export interface DBOpFrame {
  kind: string; // "idle" | "start" | "output" | "done"
  op?: string; // start: "publish"
  db?: string; // start
  all?: boolean; // start, publish only: publishing every database
  startedAt?: string; // start
  line?: string; // output
  ok: boolean; // done (always emitted so false is explicit)
  durationMs?: number /* int64 */; // done
  err?: string; // done (only when !OK)
  errorCode?: string; // done (only when !OK): stable hint key
}

//////////
// source: devdb.go

export interface DevDBProject {
  name: string;
  path: string;
  databases: string[];
}
export interface DevDBProjectsResponse {
  projects: DevDBProject[];
}
export interface DevDBMetaResponse {
  environment_path: string;
  environment_name: string;
  sql_server_image: string;
  /**
   * SQLServerPort is the container's published host port — the target
   * `orbit db publish` connects to from the host.
   */
  sql_server_port?: number /* int */;
  /**
   * SQLServerTarget is the publish target's runtime docker name. The
   * CLI resolves SA_PASSWORD by inspecting THIS container so port and
   * credentials always come from the same declared target. Empty on
   * daemons predating the field — consumers fall back to the legacy
   * sql-server name.
   */
  sql_server_target?: string;
  workspace_root: string;
  /**
   * DBConfigured mirrors the DB-workflow gate: false when the active
   * env has neither a sql-server container nor a declared sql_projects
   * target. CLI and dashboard hide the
   * DB workflow behind it. A pointer so consumers can fail OPEN when the
   * field is absent — a CLI newer than its daemon must not lock
   * users out of db commands just because the old daemon doesn't report it.
   * Interpret via WorkflowConfigured, not by dereferencing directly.
   */
  db_configured?: boolean;
  /**
   * ClaimConfigured is false when the active env has no claim section
   * (Tunlease tunnel support). The dashboard hides the Tunnels tab behind
   * it, the same way DBConfigured gates Local DB. Same pointer +
   * fail-open rule: nil (a daemon predating the field) counts as
   * configured so the tab never wrongly vanishes for
   * users on an older daemon. Interpret via ClaimSupported.
   * This DB-named response carries the tunnel gate too — the pragmatic
   * choice over a second endpoint. If a third feature needs a UI gate,
   * promote this to a general feature-meta type.
   */
  claim_configured?: boolean;
}

//////////
// source: devdb_discovery.go


//////////
// source: drift_cache.go

/**
 * DriftEntry is one database's cached diff outcome: either a structured
 * Result or a failure (Error + Code) — never both. At is the RFC3339
 * time the diff ran; Stale marks a publish/reset since then.
 */
export interface DriftEntry {
  db: string;
  result?: DiffResult;
  error?: string;
  code?: string;
  at: string;
  stale?: boolean;
}
/**
 * DriftSnapshotResponse is the body of GET /api/db/drift: every cached
 * entry in stable (by DB name) order.
 */
export interface DriftSnapshotResponse {
  entries: DriftEntry[];
}

//////////
// source: handlers_dbstate.go

/**
 * DBStateEventRequest is the body of POST /api/db-state/event.
 * CLI calls this after a DB operation (apply, reset, publish,
 * publish_clean, snapshot) succeeds or fails.
 */
export interface DBStateEventRequest {
  kind: string; // "apply" | "reset" | "publish" | "publish_clean" | "snapshot"
  db: string;
  source: any /* dbstate.Source */; // "ui" | "cli"
  status: string; // "ok" | "error"
  durationMs?: number /* int64 */;
  errorMsg?: string;
}

//////////
// source: handlers_diff.go

/**
 * DBDiffRequest is the body for POST /api/db/diff.
 */
export interface DBDiffRequest {
  db: string;
  /**
   * Script requests the full T-SQL deployment script instead of the
   * structured operation summary.
   */
  script?: boolean;
  /**
   * Analyze compares the dacpac with SQL Server to return exact object
   * operations and data-loss warnings.
   */
  analyze?: boolean;
  /**
   * FastOnly returns needs_engine instead of falling through to
   * sqlpackage. Page-entry refreshes use it so navigation stays cheap.
   */
  fast_only?: boolean;
}
/**
 * DBDiffResponse carries a structured result, a requested SQL script, or
 * NeedsEngine when a fast-only request cannot prove an answer.
 */
export interface DBDiffResponse {
  result?: DiffResult;
  script?: string;
  needs_engine?: boolean;
}

//////////
// source: handlers_publish.go

/**
 * DBPublishRequest is the body for POST /api/db/publish.
 */
export interface DBPublishRequest {
  /**
   * DB names one database; empty and ignored when All is set.
   */
  db?: string;
  force?: boolean;
  /**
   * All publishes every database from the project merge, sequentially
   * under the one op lock, stopping at the first failure.
   */
  all?: boolean;
}

//////////
// source: handlers_reset.go

/**
 * CodeResetRequiresConfirmation is returned when reset needs explicit
 * acknowledgement that local data will be discarded.
 */
export const CodeResetRequiresConfirmation = "reset_requires_confirmation";
/**
 * DBResetState is the per-database reset readiness the UI needs to render
 * ahead of a click. A missing DB cannot be reset; publish creates it.
 */
export interface DBResetState {
  exists: boolean;
}
/**
 * DBResetStateResponse maps each known database to its reset readiness.
 */
export interface DBResetStateResponse {
  states: { [key: string]: DBResetState};
}
/**
 * DBResetRequest is the body for POST /api/db/reset. The client never
 * selects the reset path. AcknowledgeDataLoss confirms the caller showed
 * that reset discards local data; the server still chooses the fastest
 * safe implementation.
 */
export interface DBResetRequest {
  db: string;
  acknowledgeDataLoss?: boolean;
}

//////////
// source: settings.go

