// Code generated by tygo. DO NOT EDIT.

//////////
// source: model.go
/*
Package tracing implements Orbit's built-in local trace store: an
in-memory ring buffer of OTLP spans, an OTLP/HTTP receiver, and query +
subscription APIs for the CLI and dashboard.

model.go holds only the wire types (exported to TypeScript via tygo). The
store and OTLP ingest live in tracing.go and otlp.go and are excluded from
tygo because they carry locks and protobuf types TS must never see.
*/

/**
 * Span is one span within a trace. Times are unix-nanoseconds (numbers in TS)
 * so the UI can lay out the waterfall without parsing timestamps.
 */
export interface Span {
  traceId: string;
  spanId: string;
  parentId?: string;
  service: string;
  name: string;
  kind?: string; // server | client | producer | consumer | internal
  startUnixNano: number /* int64 */;
  endUnixNano: number /* int64 */;
  durationMs: number /* float64 */;
  status: string; // ok | error | unset
  statusMsg?: string;
  attributes?: { [key: string]: string};
}
/**
 * TraceSummary is a row in the trace list — everything needed to render the
 * list without shipping the spans.
 */
export interface TraceSummary {
  traceId: string;
  rootService: string;
  rootName: string;
  startUnixNano: number /* int64 */;
  durationMs: number /* float64 */;
  spanCount: number /* int */;
  services: string[]; // distinct service names, first-seen order
  status: string; // ok | error
}
/**
 * Trace is a full trace: the summary fields plus every span, sorted by start
 * time. Fields mirror TraceSummary (rather than embedding it) so the JSON and
 * the tygo-generated TS stay flat — embedding would nest under a "TraceSummary"
 * key in TS while Go promotes the fields inline.
 */
export interface Trace {
  traceId: string;
  rootService: string;
  rootName: string;
  startUnixNano: number /* int64 */;
  durationMs: number /* float64 */;
  spanCount: number /* int */;
  services: string[];
  status: string;
  spans: Span[];
}
/**
 * TracingStatus is the collector health snapshot for the live indicator.
 * Domain-prefixed (not just "Status") because tygo strips the package
 * qualifier when exporting to the shared types.gen.ts namespace.
 * Configured (the env opted in) and ReceiverHealthy (the OTLP listener
 * actually bound and is serving) are deliberately separate: the receiver's
 * bind is non-fatal, so an env can be Configured yet have no live receiver
 * (e.g. port already taken and no fallback succeeded). A UI that conflates the
 * two shows "healthy" while nothing is being collected — the exact trap this
 * split closes. ActualPort is the port the receiver actually bound (may differ
 * from the configured port after fallback); it is 0 when the receiver is not
 * healthy.
 */
export interface TracingStatus {
  configured: boolean; // env opted into tracing
  receiverHealthy: boolean; // OTLP listener bound and serving
  otlpPort: number /* int */; // configured/desired port
  actualPort: number /* int */; // port actually bound; 0 when unhealthy
  receiverError?: string; // bind failure reason, when any
  traceCount: number /* int */;
  totalSpans: number /* int64 */;
  spansPerMin: number /* int */;
  lastReceivedUnixMs: number /* int64 */; // 0 = never
  /**
   * SpansDropped counts spans rejected by the ingest ceilings (oversized
   * body, per-trace span cap, or attribute-bytes cap). Non-zero means the
   * store is shedding load, not that nothing is arriving.
   */
  spansDropped: number /* int64 */;
}
