// Code generated by tygo. DO NOT EDIT.

//////////
// source: accesslog.go

/**
 * AccessLine is one inbound callback through a tunnel — a one-line summary
 * (no body). Emitted by the per-tunnel log-proxy and shown in the dashboard.
 */
export interface AccessLine {
  local_port: number /* int */;
  time: string;
  method: string;
  path: string;
  status: number /* int */;
  duration_ms: number /* int64 */;
}
/**
 * AccessLogHub keeps a bounded per-local-port ring of recent AccessLines and
 * fans new lines to SSE subscribers. Subscribe replays existing lines (all
 * ports) then streams new ones — same contract as history.Recorder.Subscribe.
 */
export interface AccessLogHub {
}

//////////
// source: handlers_tunnel.go

/**
 * Tunnel is the state for one local port. Field access requires the
 * owning TunnelManager.mu — except inside a claim/release operation,
 * where holding opMu alone is sufficient for reads: opMu serializes
 * whole operations, so no other writer can run concurrently.
 */
export interface Tunnel {
  LocalPort: number /* int */;
  ProxyPort: number /* int */;
  Paths: string[];
  Status: string;
  LastError: string;
}
/**
 * TunnelManager owns every tunnel. Lock order: opMu before mu, never
 * the reverse.
 */
export interface TunnelManager {
}
export interface ClientAPIOptions {
  gateway?: string;
  token?: string;
  insecure?: boolean;
}
export interface ClaimAPIRequest {
  local_port: number /* int */;
  paths: string[];
  gateway?: string;
  token?: string;
  insecure?: boolean;
}
export interface ReleaseAPIRequest {
  local_port?: number /* int */;
  path?: string;
  gateway?: string;
  token?: string;
  insecure?: boolean;
}
export interface ReleaseAPIResponse {
  APIResponse: any /* daemon.APIResponse */;
  released: number /* int */;
  paths: string[];
  local_port?: number /* int */;
  gateway?: string;
}
export interface TunnelView {
  local_port: number /* int */;
  proxy_port: number /* int */;
  paths: string[];
  status: string;
  last_error?: string;
}
export interface TunnelListResponse {
  gateway?: string;
  tunnels: TunnelView[];
  claims?: LocalClaimView[];
}
export interface LocalClaimView {
  paths: string[];
  owner: string;
  started_at: string;
  expires_at?: string;
  local_port: number /* int */;
  status: string;
}
export interface GlobalClaimView {
  path_prefix: string;
  owner: string;
  started_at: string;
  expires_at: string;
  mine: boolean;
}
export interface GlobalClaimsResponse {
  claims: GlobalClaimView[];
}
/**
 * TunnelFeature adapts a TunnelManager to the daemon's HTTP mux.
 */
export interface TunnelFeature {
}

//////////
// source: tunnel_config.go

/**
 * ClaimConfig configures Orbit's embedded Tunlease client. Token is optional.
 */
export interface ClaimConfig {
  gateway: string;
  token?: string;
  insecure?: boolean;
}
