// Code generated by tygo. DO NOT EDIT.

//////////
// source: settings.go

/**
 * Settings stores user preferences that persist across daemon restarts.
 */
export interface Settings {
  /**
   * WorkspaceRoot is the directory containing the team's repo checkouts.
   */
  workspace_root?: string;
  /**
   * EnvRepoURL is the git URL `orbit env sync` clones envs from. Only an
   * explicitly user-provided URL is stored here; when empty, resolution
   * falls through to ORBIT_ENV_REPO_URL and the built-in default, so a
   * default change in a new orbit release reaches users who never overrode.
   */
  env_repo_url?: string;
  env_toggles?: { [key: string]: boolean};
  service_modes?: { [key: string]: string}; // "api": "container"
  user_env?: { [key: string]: string};
  show_history?: boolean;
  /**
   * DetachedEdges is a two-level map: env → from → []to.
   * Keys are env names (e.g. "development"); values map a "from" service
   * name to the list of "to" dep names whose edge is suppressed at startup.
   * On-disk format history:
   *   v1 (flat): map[string][]string keyed "<env>/<from>" → []to
   *   v2 (nested, current): map[string]map[string][]string
   * LoadSettings auto-migrates v1 to v2 in-memory; the next Save persists v2.
   */
  detached_edges?: { [key: string]: { [key: string]: string[]}};
}

//////////
// source: wire.go
/*
Package daemon is the public wire-and-host surface of the orbit
daemon: the JSON contracts the CLI, dashboard, and extensions speak,
the socket client, settings, and the capability types a feature's
DaemonSetup consumes. The concrete HTTP server lives in the
core-private internal/daemon — it implements these contracts; nothing
here depends on it.
*/

/**
 * UpRequest is the body for POST /api/up.
 */
export interface UpRequest {
  resources: string[];
  infra_only: boolean;
  groups: string[];
}
/**
 * DownRequest is the body for POST /api/down.
 */
export interface DownRequest {
  all: boolean;
  wait: boolean;
}
/**
 * StatusResponse is the response for GET /api/status.
 */
export interface StatusResponse {
  /**
   * Epoch is the daemon's startedAt timestamp in unix-milliseconds. It
   * changes on every restart, so clients can detect when their cached
   * env-derived state belongs to a previous daemon. Milliseconds (not
   * nanoseconds) keeps the value safely within JS Number precision.
   */
  epoch: number /* int64 */;
  resources: ResourceStatus[];
  /**
   * ConfigPath identifies the environment loaded by the running daemon.
   * CLI clients compare it with their selected config before combining
   * local config with daemon state.
   */
  config_path: string;
  /**
   * ConfigStale means the loaded config has fallen behind reality (env
   * file edited, selection changed, or an API env switch left the
   * orchestrator on the previous env) — `orbit env apply` applies.
   */
  config_stale?: boolean;
  config_stale_reason?: string;
}
/**
 * ResourceKind identifies how Orbit runs a resource.
 */
export type ResourceKind = string;
export const ResourceKindContainer: ResourceKind = "container";
export const ResourceKindService: ResourceKind = "service";
/**
 * SidecarInfo represents a sidecar's UI link.
 */
export interface SidecarInfo {
  name: string;
  url: string;
}
/**
 * ResourceStatus represents a single container or service.
 */
export interface ResourceStatus {
  name: string;
  kind: ResourceKind;
  state: string;
  /**
   * PendingDependencies identifies exactly what keeps a pending resource
   * from starting, so clients can distinguish useful waiting from a
   * terminal dependency failure.
   */
  pending_dependencies?: string[];
  /**
   * StateReason says why the resource is degraded (crash message, health
   * failure, build failure); empty in every other state.
   */
  state_reason?: string;
  port_conflict?: ResourcePortConflict;
  logs_available?: boolean;
  restart_count: number /* int */;
  ports?: { [key: string]: number /* int */};
  url?: string;
  image?: string; // resolved container image; containers only
  startup_time?: string;
  uptime?: string;
  sidecars?: SidecarInfo[];
  mode?: string; // "dev" or "container" (only for dual-defined services)
  health_progress?: HealthProgressInfo;
}
/**
 * ResourcePortConflict is actionable evidence for a resource that could not
 * bind its configured host port.
 */
export interface ResourcePortConflict {
  port: number /* int */;
  resource: string;
  pid?: string;
  process?: string;
  inspect_command: string;
}
/**
 * HealthProgressInfo reports retry state for a resource that has a
 * configured health check. nil on ResourceStatus means the resource either
 * has no health check or has not yet attempted one (caller hides UI).
 */
export interface HealthProgressInfo {
  attempts: number /* int */;
  max_retries?: number /* int */;
  last_err?: string;
  /**
   * Recovering means the startup retry budget is spent but the daemon is
   * still probing and will flip the service back to healthy on success.
   * CLI waits treat degraded+recovering as "still trying", not terminal.
   */
  recovering?: boolean;
}
/**
 * LogsResponse is the response for GET /api/logs/{name}.
 */
export interface LogsResponse {
  lines: string[];
}
/**
 * APIResponse is a generic API response wrapper.
 */
export interface APIResponse {
  ok?: boolean;
  message?: string;
  error?: string;
  /**
   * AffectedResources identifies the resources accepted by a lifecycle
   * request, including dependencies selected by the daemon.
   */
  affected_resources?: string[];
  /**
   * Code is a stable, machine-readable discriminator a client can
   * switch on when the plain Error string isn't enough — e.g. the
   * reset endpoint's "reset_requires_recreate". Empty for most errors.
   */
  code?: string;
}

//////////
// source: wire_more.go

/**
 * DoctorCheckStatus represents the result of a health check.
 */
export type DoctorCheckStatus = string;
export const CheckPass: DoctorCheckStatus = "pass";
export const CheckFail: DoctorCheckStatus = "fail";
export const CheckWarn: DoctorCheckStatus = "warn";
export const CheckInfo: DoctorCheckStatus = "info";
/**
 * DoctorCheck is a single health check result.
 */
export interface DoctorCheck {
  name: string;
  status: DoctorCheckStatus;
  message: string;
  hint?: string;
}
/**
 * DoctorResponse is the response for GET /api/doctor.
 */
export interface DoctorResponse {
  checks: DoctorCheck[];
  ran_at: string;
}
/**
 * TraceLogLine is one log line that belongs to a trace, with the service it
 * came from so merged views stay attributable.
 */
export interface TraceLogLine {
  service: string;
  line: string;
}
/**
 * TraceLogsResponse is the response for GET /api/traces/{id}/logs.
 */
export interface TraceLogsResponse {
  lines: TraceLogLine[];
}
/**
 * EnvInfo describes one available env config file.
 */
export interface EnvInfo {
  name: string;
  path: string;
  current: boolean;
  previewOnly: boolean;
}
/**
 * EnvsResponse is returned by GET /api/envs.
 */
export interface EnvsResponse {
  current?: string;
  running: number /* int */; // count of non-stopped services
  envs: EnvInfo[];
}
/**
 * VersionResponse reports the running daemon's build and a binary Orbit can
 * order after it. Older or incomparable builds are omitted so
 * clients never recommend a restart that could downgrade the user.
 */
export interface VersionResponse {
  running: string;
  on_disk?: string;
  on_disk_path?: string;
  update_available: boolean;
}
/**
 * EnvToggleUpdateRequest is the PUT body.
 */
export interface EnvToggleUpdateRequest {
  service: string;
  var: string;
  enabled: boolean;
}
/**
 * EdgeDetachRequest is the PUT body for /api/edges/{from}/{to}.
 */
export interface EdgeDetachRequest {
  /**
   * Env is accepted for back-compat but ignored server-side; the server
   * derives the env from its currently loaded config (currentEnvName()).
   * Clients SHOULD continue sending it so old daemons keep working.
   */
  env: string;
  detached: boolean;
}
/**
 * ServiceModeRequest is the body for PUT /api/service-mode/{name}.
 */
export interface ServiceModeRequest {
  mode: string; // "dev" or "container"
}
/**
 * SettingsResponse is the /api/settings response. Fields duplicate APIResponse
 * rather than embed it so the wire shape stays flat for TS codegen.
 */
export interface SettingsResponse {
  ok?: boolean;
  message?: string;
  error?: string;
}
/**
 * ResourceSchemaVersion versions the snapshot wire shape. Additive changes
 * (new fields, new resource types, new state values) do not bump it —
 * consumers must tolerate unknown values; renames and removals do.
 */
export const ResourceSchemaVersion = 1;
/**
 * ResourceSnapshot is the uniform, type-agnostic view of one thing orbit
 * knows about: a container, a service, an external system, a database, a
 * rebuild job, a tunnel, a claimed route. Consumers render name / type /
 * state / properties generically without knowing concrete resource kinds —
 * the design that lets a future integration surface its own resources
 * without touching any renderer (see docs/pilot-elastiflix.md and the
 * extension pre-study). This endpoint coexists with the purpose-built
 * /api/status and /api/graph views; it does not replace them.
 */
export interface ResourceSnapshot {
  name: string;
  /**
   * Type is an open vocabulary: container, service, external, database,
   * job, tunnel, route today. Consumers must render unknown types
   * generically rather than reject them.
   */
  type: string;
  state?: string;
  state_reason?: string;
  /**
   * Parent groups a resource under another (database → sql-server,
   * route → tunnel). Empty for top-level resources.
   */
  parent?: string;
  depends_on?: string[];
  urls?: string[];
  /**
   * Properties are display-oriented facts. Flat k/v on purpose — nested
   * payloads belong in purpose-built endpoints; what doesn't fit here is
   * the measured limit of generic rendering. Keys are opaque identifiers:
   * consumers must not parse them (the "port:redis" colon is a naming
   * convention, not a protocol).
   */
  properties?: { [key: string]: string};
  /**
   * Health is the one sanctioned nested exception to the flat contract:
   * it is shared verbatim with /api/status, and its Recovering flag is
   * load-bearing for wait semantics — flattening would fork the shape.
   */
  health?: HealthProgressInfo;
}
/**
 * ResourcesResponse is the GET /api/resources payload.
 */
export interface ResourcesResponse {
  schema_version: number /* int */;
  env: string;
  resources: ResourceSnapshot[];
}
