#!/usr/bin/env bash
# Regenerate NOTICE from the licenses actually shipped in the binary: Go modules
# linked into the CLI plus the dashboard's runtime dependencies, which are
# embedded as minified assets. Minification drops most copyright headers, so
# NOTICE is where those attributions live.
#
# Run after changing dependencies; `make test-notice` fails when it is stale.
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$repo_root"

out="${1:-NOTICE}"
tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

{
  echo "# Third-party notices"
  echo
  echo "Orbit is distributed under the MIT license (see LICENSE). The Orbit"
  echo "binary also embeds the dependencies below. This file is generated by"
  echo "scripts/gen-notice.sh — edit that script, not this file."
  echo
  echo "## Go modules"
  echo
} >"$tmp"

go run github.com/google/go-licenses@latest report ./cmd/orbit 2>/dev/null |
  sort -t, -k1,1 |
  awk -F, 'NF>=3 && $1 != "" { printf "- %s — %s\n", $1, $3 }' >>"$tmp"

{
  echo
  echo "## Dashboard runtime dependencies"
  echo
} >>"$tmp"

pnpm --dir ui licenses list --prod --json 2>/dev/null |
  node -e '
    let raw = ""
    process.stdin.on("data", (chunk) => (raw += chunk)).on("end", () => {
      const grouped = JSON.parse(raw)
      const rows = []
      for (const [license, packages] of Object.entries(grouped)) {
        for (const pkg of packages || []) {
          rows.push({ name: pkg.name, license })
        }
      }
      rows.sort((a, b) => a.name.localeCompare(b.name))
      const seen = new Set()
      for (const row of rows) {
        if (seen.has(row.name)) continue
        seen.add(row.name)
        process.stdout.write(`- ${row.name} — ${row.license}\n`)
      }
    })
  ' >>"$tmp"

mv "$tmp" "$out"
trap - EXIT
echo "wrote $out"
